---
# values-dev.yaml
replicaCount: 2
deploymentStrategy:
  type: blueGreen
blueGreen:
  autoPromotionSeconds: 10
  previewService:
    type: NodePort
    nodePort: 30100

ingress:
  enabled: false

argocd:
  destination:
    namespace: vote-dev
