---
# templates/ingress.yaml
{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "vote-app.fullname" . }}
  labels:
    {{- include "vote-app.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  {{- if .Values.ingress.tls.enabled }}
  tls:
    - secretName: {{ .Values.ingress.tls.secretName }}
  {{- end }}
  rules:
    - http:
        paths:
          {{- if eq .Values.deploymentStrategy.type "blueGreen" }}
          - path: {{ .Values.ingress.pathPrefix }}(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: {{ include "vote-app.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
          {{- if .Values.blueGreen.previewService.enabled }}
          - path: {{ .Values.ingress.pathPrefix }}/preview(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: {{ include "vote-app.fullname" . }}-preview
                port:
                  number: {{ .Values.blueGreen.previewService.port }}
          {{- end }}
          {{- else if eq .Values.deploymentStrategy.type "canary" }}
          - path: {{ .Values.ingress.pathPrefix }}(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: {{ include "vote-app.fullname" . }}-stable
                port:
                  number: {{ .Values.canary.stableService.port }}
          - path: {{ .Values.ingress.pathPrefix }}/canary(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: {{ include "vote-app.fullname" . }}-canary
                port:
                  number: {{ .Values.canary.canaryService.port }}
          {{- end }}
{{- end }}
  template:
    metadata:
      labels:
        {{- include "vote-app.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
