---
# templates/ingress.yaml
{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "vote-app.fullname" . }}
  labels:
    {{- include "vote-app.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - http:
        paths:
          {{- if eq .Values.deploymentStrategy.type "blueGreen" }}
          - path: {{ .Values.ingress.pathPrefix }}(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: {{ include "vote-app.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
          {{- if .Values.blueGreen.previewService.enabled }}
          - path: {{ .Values.ingress.pathPrefix }}/preview(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: {{ include "vote-app.fullname" . }}-preview
                port:
                  number: {{ .Values.service.port }}
          {{- end }}
          {{- else if eq .Values.deploymentStrategy.type "canary" }}
          - path: {{ .Values.ingress.pathPrefix }}(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: {{ include "vote-app.fullname" . }}-stable
                port:
                  number: {{ .Values.service.port }}
          - path: {{ .Values.ingress.pathPrefix }}/canary(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: {{ include "vote-app.fullname" . }}-canary
                port:
                  number: {{ .Values.service.port }}
          {{- end }}
{{- end }}
