---
# templates/service.yaml
{{- if eq .Values.deploymentStrategy.type "blueGreen" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "vote-app.fullname" . }}
  labels:
    {{- include "vote-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
  selector:
    {{- include "vote-app.selectorLabels" . | nindent 4 }}
{{- end }}

